### ISSUE TITLE
Starting/stopping Advertising causes memory leak

### ISSUE THREAD

**Issue by Adamsc73** [h2zero/NimBLE-Arduino#337] opened 2022-01-18 17:31 UTC
I have a project in which I need to start up a BLE Server, then shut it down a while later, then start it back up, etc...  This needs to happen many times.  In attempting this, it appears that there is a memory leak when I stop the advertising.  If I run the following code, but comment out the BLEDevice::startAdvertising() line, there is no memory leak.  If I have that line in there, there is a leak.  Note, for this example code, I never actually connect to the Server.  I'm just running it to see the heap reduction.  Here is a simplified code example I wrote up that demonstrates the problem.  Any help would be greatly appreciated!  Thank you in advance!
```
/*
    Based on Neil Kolban example for IDF: https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLE%20Tests/SampleServer.cpp
    Ported to Arduino ESP32 by Evandro Copercini
    updates by chegewara
*/

/** NimBLE differences highlighted in comment blocks **/

#include <NimBLEDevice.h>

// See the following for generating UUIDs:
// https://www.uuidgenerator.net/

#define SERVICE_UUID        "4fafc201-1fb5-459e-8fcc-c5c9c331914b"
#define CHARACTERISTIC_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a8"

BLEServer *pServer;
BLEService *pService;
BLECharacteristic *pCharacteristic;

void StartDevice()
{
  BLEDevice::init("Long name works now");

  pServer = BLEDevice::createServer();
  pService = pServer->createService(SERVICE_UUID);
  pCharacteristic = pService->createCharacteristic(
                                        CHARACTERISTIC_UUID,
                                  /***** Enum Type NIMBLE_PROPERTY now *****      
                                        BLECharacteristic::PROPERTY_READ   |
                                        BLECharacteristic::PROPERTY_WRITE  
                                        );
                                  *****************************************/
                                        NIMBLE_PROPERTY::READ |
                                        NIMBLE_PROPERTY::WRITE 
                                       );

  pCharacteristic->setValue("Hello World says Neil");
  pService->start();
  // BLEAdvertising *pAdvertising = pServer->getAdvertising();  // this still is working for backward compatibility
  BLEAdvertising *pAdvertising = BLEDevice::getAdvertising();
  pAdvertising->addServiceUUID(SERVICE_UUID);
  pAdvertising->setScanResponse(true);
  pAdvertising->setMinPreferred(0x06);  // functions that help with iPhone connections issue
  pAdvertising->setMaxPreferred(0x12);

  //**************************************************************
  // If I comment out this line, no memory leak happens!
  //**************************************************************
  BLEDevice::startAdvertising();  
  
  Serial.println(">>> Device Started <<<");
}

void StopDevice()
{
    BLEDevice::stopAdvertising();

    BLEDevice::getAdvertising()->removeServiceUUID(pService->getUUID());

    pService->removeCharacteristic(pCharacteristic);
    pServer->removeService(pService);

    BLEDevice::deinit(true);

    Serial.println(">>> Device Stopped <<<");
}

void setup() {
  Serial.begin(115200);
  Serial.println("Starting BLE work!");
}

int cnt = 0;
void loop() 
{
  // put your main code here, to run repeatedly:
  if (cnt == 0)
  { // Start the device.
    StartDevice();
  }
  if (cnt == 2)
  { // Stop the device.
    StopDevice();
  }

  cnt++;
  if (cnt >= 4)
  {
    cnt = 0;
  }

  Serial.printf("Free Heap: %d\r\n", ESP.getFreeHeap());
  delay(2000);
}
```

Here is a snippet of the results over the serial port.  As can be seen, the heap drops 60 bytes on each pass.
```
>>> Device Started <<<
Free Heap: 220480
Free Heap: 220480
>>> Device Stopped <<<
Free Heap: 248208
Free Heap: 252672
>>> Device Started <<<
Free Heap: 220420
Free Heap: 220420
>>> Device Stopped <<<
Free Heap: 248148
Free Heap: 252612
>>> Device Started <<<
Free Heap: 220360
Free Heap: 220360
>>> Device Stopped <<<
Free Heap: 248088
Free Heap: 252552
>>> Device Started <<<
Free Heap: 220300
Free Heap: 220300
>>> Device Stopped <<<
Free Heap: 252492
Free Heap: 252492
>>> Device Started <<<
Free Heap: 220240
Free Heap: 220240
>>> Device Stopped <<<
Free Heap: 252432
Free Heap: 252432
```

**Comment by h2zero** [comment] 2022-01-18 18:02
There is a memory leak in versions earlier than 1.3.5 of this repo that occur when reinitializing the BLE stack. If you are using an older version please try updating and post back with your results.

**Comment by Adamsc73** [comment] 2022-01-18 18:26
Thank you for the quick help.  I had previously run across some other information about those memory leaks and had modified my code to fix it.  I didn't realize 1.3.5 had been released.  I updated to that and still have the same memory leak.

**Comment by h2zero** [comment] 2022-01-18 21:17
Thanks, I have reproduced and identified the issue and will include it in the next release.

As a workaround, in your code you can remove these lines:
```
    BLEDevice::stopAdvertising();

    BLEDevice::getAdvertising()->removeServiceUUID(pService->getUUID());

    pService->removeCharacteristic(pCharacteristic);
    pServer->removeService(pService);
```
They aren't necessary if you'll just be deinitializing the stack anyway, it'll take care of that for you.

The memory leak specifically is caused by some missing `delete` calls when using.
```
    pService->removeCharacteristic(pCharacteristic);
    pServer->removeService(pService);
```

**Comment by Adamsc73** [comment] 2022-01-18 21:55
Thank you so much for looking into it so quickly!  Can you indicate what delete calls there needs to be so I can add them and get it working until the next release?

**Comment by h2zero** [comment] 2022-01-18 22:42
You're very welcome! The patch has been applied and queued for release. 

I will close this issue now, feel free to re-open in the future if necessary.

**Closed** 2022-01-18 22:42 UTC
