### ISSUE TITLE
BLE UART example

### ISSUE THREAD

**Issue by darshan-mirajkar** [h2zero/NimBLE-Arduino#100] opened 2020-07-27 18:02 UTC
How can we use ble UART example for UART 1 / UART 2 of esp32?

**Comment by h2zero** [comment] 2020-07-27 23:10
That example came from the original library. I believe it was intended to be used with the nRF UART app.

**Comment by h2zero** [comment] 2020-12-29 00:59
Closing this as resolved.

**Closed by h2zero** 2020-12-29 00:59 UTC
