### ISSUE TITLE
max characters to write in a characteristic

### ISSUE THREAD

**Issue by ccssw** [h2zero/NimBLE-Arduino#148] opened 2020-11-25 10:10 UTC
I found that I can only write up to 216 characters in a characteristic, otherwise the callback is not run. Is it possible to enlarge it?

**Comment by h2zero** [comment] 2020-11-26 01:24
That doesn't seem right, I'm able to write from a client device and receive them on the server. What is the MTU size?

**Comment by ccssw** [comment] 2020-11-26 09:54
How can I get the MTU size?

**Comment by ccssw** [comment] 2020-11-26 11:45
When I try to set the MTU with `NimBLEDevice::setMTU(BLE_ATT_MTU_MAX)` size I get:

`
D NimBLEDevice: ">> setLocalMTU: 527"
assertion "mu->handle" failed: file ".pio/libdeps/noukee/NimBLE-Arduino/src/porting/npl/freertos/src/npl_os_freertos.c", line 185, function: npl_freertos_mutex_pend
`

**Comment by h2zero** [comment] 2020-11-27 00:11
That's a very strange error. I have not had this issue nor seen any reports regarding this previously. I will do what I can to reproduce.

As for your initial issue, what is your setup are you connecting with a phone to the esp32 or another device? If from a phone you may need to use long write if the data size is greater than MTU-3.

**Comment by h2zero** [comment] 2020-12-01 00:05
Ok, so the limit you see is due most likely to the phone MTU. You cannot change it as the spec states that the lowest of the 2 MTU's is the one that is used.

In that situation you will need to use a long write procedure.

**Comment by ccssw** [comment] 2020-12-01 09:04
> what is your setup are you connecting with a phone to the esp32 or another device?

Yes, it's a smart phone.

**Comment by h2zero** [comment] 2020-12-29 01:45
@ccssw any updates on this?

**Comment by ccssw** [comment] 2021-01-11 11:45
Requesting the MTU to 517 fixed the issue for now.

**Comment by chegewara** [comment] 2021-01-11 11:59
Max MTU is 517 IIRC.

**Comment by h2zero** [comment] 2021-02-01 05:12
>Max MTU is 517 IIRC.

Max for NimBLE is 527 to accomodate signed writes, which we don't do (yet) so 517 works 😄 

Going to close this as it seems to be resolved.

**Closed by h2zero** 2021-02-01 05:12 UTC
